### ISSUE TITLE
Can't re-build project without Maven "clean" phase

### ISSUE THREAD

**Issue by wodzuu** [ethlo/eclipselink-maven-plugin#44]
**How to reproduce**

1. run `mvn clean package`
2. run `mvn package`

**Expected behaviour**
The second command succeeds

**Actual behaviour**
The command execution fails with error message
```
[ERROR] Failed to execute goal com.ethlo.persistence.tools:eclipselink-maven-plugin:3.0.2:modelgen (modelgen) on project security: Processing failed: 
[ERROR] Note: Hibernate JPA 2 Static-Metamodel Generator 6.2.0.CR4
[ERROR] warning: Unable to parse persistence.xml: Unable to perform unmarshalling at line number 0 and column 0. Message: null
[ERROR] error: Problem with Filer: Attempt to recreate a file for type com.my.Entity_
```

**Workaround**
Include the `clean` phase each time you build the project

**Comment by ethlo** [comment]
Unfortunately this seems to be a bug/limitation in the Hibernate library.

**Comment by claudioweiler** [comment]
This breaks incremental builds also:

```
Failed to execute mojo com.ethlo.persistence.tools:eclipselink-maven-plugin:3.0.2:modelgen {execution: generate-jpa-metamodels} (com.ethlo.persistence.tools:eclipselink-maven-plugin:3.0.2:modelgen:generate-jpa-metamodels:generate-sources)

org.eclipse.core.runtime.CoreException: Failed to execute mojo com.ethlo.persistence.tools:eclipselink-maven-plugin:3.0.2:modelgen {execution: generate-jpa-metamodels}
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$0(MavenExecutionContext.java:291)
	at ...
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: org.apache.maven.plugin.MojoExecutionException: Processing failed: 
Note: Hibernate JPA 2 Static-Metamodel Generator 6.2.0.CR4
error: Problem with Filer: Attempt to recreate a file for type ...
	at com.ethlo.persistence.tools.eclipselink.EclipselinkModelGenMojo.execute(EclipselinkModelGenMojo.java:182)
	at ...
	... 32 more
```

Hibernate says this is a javac behavior:
https://discourse.hibernate.org/t/hibernate-jpamodelgen-error-diagnostic-error-problem-with-filer-attempt-to-recreate-a-file-for-type/6624/7

Don't know where javac enters this, this is annotation processor, right?

But, why this works with 2.X versions and not with 3.X versions?

**Comment by claudioweiler** [comment]
Workaround doesn't work for run configuration ("Run As" context menu).

Default Maven run configurations do not include "clean" goal.

Custom run configurations with "clean" goal gets race conflict with Eclipse incremental build.
